autogenerate:
  prompts:
    outfile: tests/e2e/prompts.py

    prompts:
      - id: used-by-ci-dont-delete
        major_version: 6

      - id: used-by-ci-dont-delete-with-tools
        major_version: 1

      - id: used-by-ci-dont-delete-no-params
        major_version: 1

      - id: text-summarization
        dangerously_use_undeployed_revision: latest

      - id: question-answerer
        dangerously_use_undeployed_revision: clvodtv700003a2z02fumceby

autogenerate_v2:
  prompts:
    outfile: tests/e2e/prompts_v2.py
    app_id: "nwn7m2i5axch0fen3oqd03da"
    
    prompts:
      - id: question-answerer
        major_version: 1
