autogenerate:
  prompts:
    outfile: tests/e2e/prompts.py

    prompts:
      - id: used-by-ci-dont-delete
        major_version: 4

      - id: used-by-ci-dont-delete-no-params
        major_version: 1

      - id: text-summarization
        dangerously_use_undeployed_revision: latest

      - id: question-answerer
        dangerously_use_undeployed_revision: clvodtv700003a2z02fumceby
