autogenerate:
  prompts:
    outfile: e2e/prompts.py

    prompts:
      - id: used-by-ci-dont-delete
        major_versions:
          - 2

      - id: used-by-ci-dont-delete-no-params
        major_versions:
          - 1
