name: Get recent PyPI versions of a package

inputs:
  package:
    required: true
  version-filter:
    required: true
  num-versions:
    required: true
    default: 3

outputs:
  versions:
    value: ${{ steps.versions.outputs.versions }}
    description: List of version numbers as JSON array

runs:
  using: composite

  steps:
    - id: versions
      run: |
        versions=$( \
          curl -s https://pypi.org/pypi/${{ inputs.package }}/json | \
          jq -r '.releases | keys | .[] | select(startswith("${{ inputs.version-filter }}"))' | \
          sort -V | \
          tail -n ${{ inputs.num-versions }} | \
          jq -ncR '[inputs]' \
        )
        echo "versions=$versions" >> $GITHUB_OUTPUT
      shell: bash
