API_ENDPOINT = "https://api.autoblocks.ai"
INGESTION_ENDPOINT = "https://ingest-event.autoblocks.ai"
AUTOBLOCKS_INGESTION_KEY = "AUTOBLOCKS_INGESTION_KEY"
AUTOBLOCKS_SIMULATION_ID = "AUTOBLOCKS_SIMULATION_ID"
