from typing import List, Optional

import pydantic


class AutogeneratePromptConfig(pydantic.BaseModel):
    """Configuration for a single prompt to be autogenerated in V2."""
    model_config = pydantic.ConfigDict(coerce_numbers_to_str=True)

    id: str
    major_version: Optional[str] = None
    dangerously_use_undeployed_revision: Optional[str] = None


class AutogeneratePromptsConfig(pydantic.BaseModel):
    """Configuration for autogenerating multiple prompts in V2."""
    outfile: str
    app_id: str  # Required for V2
    prompts: List[AutogeneratePromptConfig] 